# -*- coding: utf-8 -*-
"""FIGURA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PsU5ow7-MQLeEbM1WnhsTX6cKgpRDYW3
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4
# !pip install geopandas

import matplotlib.pyplot as plt
import xarray as xr
import pandas as pd
import numpy as np
import geopandas as gpd

from google.colab import drive
drive.mount('/content/drive')

ruta_Sudamerica = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/TPM_II/datos/shps/South_America.shp"
Sudamerica = gpd.read_file(ruta_Sudamerica)

lugar = Sudamerica.plot(facecolor="none",edgecolor="black")

ruta_DEM = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/TPM_II/datos/Spatial_co_variables/DEM.nc"
curvas = xr.open_dataset(ruta_DEM)
curvas

curvas.rename({'DEM':'Altitude'})

curvas = curvas.rename({'DEM':'Altitude'})

fig, ax = plt.subplots(1, 1, figsize=(10, 8))
curvas.Altitude.plot(ax=ax,cmap="terrain")
lugar = Sudamerica.plot(ax=ax,facecolor="none",edgecolor="black")
minx, miny, maxx, maxy = -72, -18.5, -67, -12
ax.set_xlim(minx, maxx)
ax.set_ylim(miny, maxy)