# -*- coding: utf-8 -*-
"""FIGURA3_proceso.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q0Kp0c88Ll_DLGgWiCKXz5AcAaRtm5qA

# Instalación y conexión a drive
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4
# !pip install geopandas

import matplotlib.pyplot as plt
import xarray as xr
import pandas as pd
import numpy as np
import geopandas as gpd

from google.colab import drive
drive.mount('/content/drive')

"""# Abriendo los shapefiles y NETCDF

## Shapefile
"""

ruta_Sudamerica = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/TPM_II/datos/shps/South_America.shp"
Sudamerica = gpd.read_file(ruta_Sudamerica)

ruta_lago = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/Tareas Huerta/lago_titicaca/lago_titicaca_sideteva_puno.shp"
lago_titicaca = gpd.read_file(ruta_lago)
lago_titicaca = lago_titicaca.to_crs("EPSG:4326")

"""## NETCDF"""

ruta_pp = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/Tareas Huerta/PISCO/piscov2p1(prec).nc"
PISCO_pp = xr.open_dataset(ruta_pp,decode_times=False)
PISCO_pp

PISCO_pp=PISCO_pp.rename({"X":"longitude","Y":"latitude","T":"time"})
PISCO_pp #corregir el tema de las coordenadas

PISCO_pp["time"] = pd.date_range(start="1981-01-01",freq="1M", periods= 432)
PISCO_pp #me parece que el periods es el numero de meeses, tmb sale indicado en la tabla
#cambiando eje temporal

"""# Figura pp acumulado"""

pp_filtro=PISCO_pp.sel(time=slice('1981-06-01T00:00:00.000000000','2010-05-31T12:00:00.000000000'))
pp_filtro

"""## Agrupar por estación"""

pp_filtro.groupby('time.season')

pp_summer = pp_filtro.groupby('time.season').mean(dim='time').sel(season='DJF')
pp_summer

pp_winter = pp_filtro.groupby('time.season').mean(dim='time').sel(season='JJA')
pp_winter

pp_spring = pp_filtro.groupby('time.season').mean(dim='time').sel(season='SON')
pp_spring

pp_autumn = pp_filtro.groupby('time.season').mean(dim='time').sel(season='MAM')
pp_autumn

"""## Avance pp DJF"""

fig, ax = plt.subplots(1, 1, figsize=(10, 8))
pp_summer.Prec.plot(ax=ax, cmap ="YlGnBu", vmin=150, vmax=1100, add_colorbar=False)
lugar = Sudamerica.plot(ax=ax,facecolor="none",edgecolor="black")
lago = lago_titicaca.plot(ax=ax,facecolor="paleturquoise",edgecolor="black")
minx, miny, maxx, maxy = -73.5, -18.5, -67.95, -12.55
ax.set_xlim(minx, maxx)
ax.set_ylim(miny, maxy)
ax.set_title("")

"""# RESULTADO FINAL"""

from mpl_toolkits.axes_grid1 import make_axes_locatable

from mpl_toolkits.mplot3d import axes3d
fig, axs = plt.subplots(1, 4, figsize=(18, 5))
#invierno
ax1 = axs[0]
pp_winter.Prec.plot(ax=ax1, cmap ="YlGnBu", vmin=0,vmax=550,add_colorbar=False)
lugar = Sudamerica.plot(ax=ax1,facecolor="none",edgecolor="black")
lago = lago_titicaca.plot(ax=ax1,facecolor="paleturquoise",edgecolor="black")
minx, miny, maxx, maxy =  -73.5, -18.5, -67.95, -12.55
ax1.set_xlim(minx, maxx)
ax1.set_ylim(miny, maxy)
ax1.set_ylabel("precipitation sum", size=14)
ax1.set_xlabel("")
axs[0].set_title('(a)', loc='left', fontsize = 15)

#primavera
ax2 = axs[1]
pp_spring.Prec.plot(ax=ax2, cmap ="YlGnBu",vmin=0,vmax=550, add_colorbar=False)
lugar = Sudamerica.plot(ax=ax2,facecolor="none",edgecolor="black")
lago = lago_titicaca.plot(ax=ax2,facecolor="paleturquoise",edgecolor="black")
minx, miny, maxx, maxy =  -73.5, -18.5, -67.95, -12.55
ax2.set_xlim(minx, maxx)
ax2.set_ylim(miny, maxy)
ax2.set_ylabel("")
ax2.set_xlabel("")
axs[1].set_title('(b)', loc='left', fontsize = 15)

#verano
ax3 = axs[2]
pp_summer.Prec.plot(ax=ax3, cmap ="YlGnBu",vmin=0,vmax=550, add_colorbar=False)
lugar = Sudamerica.plot(ax=ax3,facecolor="none",edgecolor="black")
lago = lago_titicaca.plot(ax=ax3,facecolor="paleturquoise",edgecolor="black")
minx, miny, maxx, maxy =  -73.5, -18.5, -67.95, -12.55
ax3.set_xlim(minx, maxx)
ax3.set_ylim(miny, maxy)
ax3.set_ylabel("")
ax3.set_xlabel("")
axs[2].set_title('(c)', loc='left', fontsize = 15)

#autumn
ax4 = axs[3]
prec = pp_autumn.Prec.plot(ax=ax4, cmap ="YlGnBu",vmin=0,vmax=550,add_colorbar=False)
lugar = Sudamerica.plot(ax=ax4,facecolor="none",edgecolor="black")
lago = lago_titicaca.plot(ax=ax4,facecolor="paleturquoise",edgecolor="black")
minx, miny, maxx, maxy =  -73.5, -18.5, -67.95, -12.55
ax4.set_xlim(minx, maxx)
ax4.set_ylim(miny, maxy)
ax4.set_ylabel("")
ax4.set_xlabel("")
axs[3].set_title('(d)', loc='left', fontsize = 15)


fig.colorbar(prec, ax=axs, label = "mm", fraction=0.02, pad=0.02)