# -*- coding: utf-8 -*-
"""FIGURA2_proceso.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10vg3D1UvAZsyaQqL4tTXKrW8uVAnVdXO

# Librerias y conexión a drive
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4
# !pip install geopandas

import matplotlib.pyplot as plt
import xarray as xr
import pandas as pd
import numpy as np
import geopandas as gpd

from google.colab import drive
drive.mount('/content/drive')

"""# Abriendo los archivos

## Shapefile
"""

ruta_Sudamerica = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/TPM_II/datos/shps/South_America.shp"
Sudamerica = gpd.read_file(ruta_Sudamerica)

ruta_lago = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/Tareas Huerta/lago_titicaca/lago_titicaca_sideteva_puno.shp"
lago_titicaca = gpd.read_file(ruta_lago)

lago_titicaca.crs

lago_titicaca = lago_titicaca.to_crs("EPSG:4326")

lago_titicaca.plot(facecolor="aqua")

"""## NETCDF"""

ruta_tmax = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/TPM_II/datos/PISCO_temperature/tx/PISCOdtx_v1.1.nc"
PISCO_tmax = xr.open_dataset(ruta_tmax)
PISCO_tmax

ruta_pp = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/Tareas Huerta/PISCO/piscov2p1(prec).nc"
PISCO_pp = xr.open_dataset(ruta_pp,decode_times=False)
PISCO_pp

PISCO_pp=PISCO_pp.rename({"X":"longitude","Y":"latitude","T":"time"})
PISCO_pp #corregir el tema de las coordenadas

PISCO_pp["time"] = pd.date_range(start="1981-01-01",freq="1M", periods= 432)
PISCO_pp

ruta_tmin = "/content/drive/MyDrive/2022 II/4. Técnicas de programación 2/Tareas Huerta/PISCO/piscov1p1(tmin).nc"
PISCO_tmin = xr.open_dataset(ruta_tmin, decode_times=False)
PISCO_tmin

PISCO_tmin = PISCO_tmin.rename({"X":"longitude","Y":"latitude","T":"time"})
PISCO_tmin #corregir el tema de las coordenadas

PISCO_tmin["time"] = pd.date_range(start="1981-01-01",freq="1M", periods= 432)
PISCO_tmin

"""#Figura 2a: Diagrama clim

## Temp maxima
"""

tmax_filtro=PISCO_tmax.sel(time=slice('1981-06-01T00:00:00.000000000','2010-05-31T12:00:00.000000000'))
tmax_filtro

tmax_clim = tmax_filtro.groupby('time.month').mean(dim='time')
tmax_clim

tmax_graph = tmax_clim.sel(latitude=slice(-12.55,-18.65),
                             longitude=slice(-73.55,-67.55))
tmax_graph

len(tmax_graph["tx"])

tmax_graph.to_dataframe()

tmax_monthly = tmax_graph.mean(dim=("latitude","longitude")).tx
tmax_monthly

tmax_monthly.plot()

tmax_graph['month'] = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
tmax_graph

tmax_monthly = tmax_graph.mean(dim=("latitude","longitude"))
tmax_monthly

tmax_monthly.tx.plot()

"""##tmin"""

tmin_filtro=PISCO_tmin.sel(time=slice('1981-06-01','2010-05-31'))
tmin_filtro

tmin_clim = tmin_filtro.groupby('time.month').mean(dim='time')
tmin_clim

tmin_graph = tmin_clim.sel(latitude=slice(-12.55,-18.65),
                             longitude=slice(-73.55,-67.55))
tmin_graph

tmin_monthly = tmin_graph.mean(dim=("latitude","longitude"))
tmin_monthly

tmin_monthly.tmin.plot()

tmin_monthly["tmin"].to_numpy()

fig, ax = plt.subplots(figsize = (7, 10))

x = np.arange(1,13)
y = tmin_monthly["tmin"].to_numpy()
plt.plot(x,y)
ax.set_xlim(0,20)

"""##pp"""

PISCO_pp.Prec.sel(time= slice('1981-06-01', '2010-05-31')).groupby('time.month').mean('time')

pp_clim = PISCO_pp.sel(time= slice('1981-06-01', '2010-05-31')).groupby('time.month').mean('time')
pp_clim

pp_graph = pp_clim.sel(latitude=slice(-12.55,-18.65),
                             longitude=slice(-73.55,-67.55))
pp_graph

pp_graph['month'] = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
pp_graph

pp_graph["Prec"][0].to_numpy()

pp_graph["Prec"][0][0].to_numpy()

pp_graph["Prec"][0][0].to_numpy()

fig, ax = plt.subplots(1)

x9 =pp_graph["Prec"][0][0].to_numpy() 

ax.boxplot(x9)

fig, ax = plt.subplots(figsize = (7, 10))

x1 = pp_graph["Prec"][0][0].to_numpy()
x2 = pp_graph["Prec"][1][0].to_numpy()
x3 = pp_graph["Prec"][2][0].to_numpy()
x4 = pp_graph["Prec"][3][0].to_numpy()
x5 = pp_graph["Prec"][4][0].to_numpy()
x6 = pp_graph["Prec"][5][0].to_numpy()
x7 = pp_graph["Prec"][6][0].to_numpy()
x8 = pp_graph["Prec"][7][0].to_numpy()
x9 = pp_graph["Prec"][8][0].to_numpy()
x10 = pp_graph["Prec"][9][0].to_numpy()
x11 = pp_graph["Prec"][10][0].to_numpy()
x12 = pp_graph["Prec"][11][0].to_numpy()
all_x = [x1,x2,x3,x4,x5,x6,x7,x8,x9, x10, x11, x12]
box= ax.boxplot(all_x)

ax.set_xsticks = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
plt.title("Diagrama de cajas")

"""## Agrupar las 3 graficas en 1 """

fig, ax = plt.subplots(figsize = (7, 10))

x1 = pp_graph["Prec"][0][0].to_numpy()
x2 = pp_graph["Prec"][1][0].to_numpy()
x3 = pp_graph["Prec"][2][0].to_numpy()
x4 = pp_graph["Prec"][3][0].to_numpy()
x5 = pp_graph["Prec"][4][0].to_numpy()
x6 = pp_graph["Prec"][5][0].to_numpy()
x7 = pp_graph["Prec"][6][0].to_numpy()
x8 = pp_graph["Prec"][7][0].to_numpy()
x9 = pp_graph["Prec"][8][0].to_numpy()
x10 = pp_graph["Prec"][9][0].to_numpy()
x11 = pp_graph["Prec"][10][0].to_numpy()
x12 = pp_graph["Prec"][11][0].to_numpy()
all_x = [x1,x2,x3,x4,x5,x6,x7,x8,x9, x10, x11, x12]

meses = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
box= ax.boxplot(all_x, patch_artist=True, labels=meses)
ax.set_ylabel("mm",rotation=0, ha='left', y=1)

fig, ax = plt.subplots(figsize=(9, 6))
ax2 = ax.twinx()  
ax2.set_ylim(0, 25)

x1 = pp_graph["Prec"][0][0].to_numpy()
x2 = pp_graph["Prec"][1][0].to_numpy()
x3 = pp_graph["Prec"][2][0].to_numpy()
x4 = pp_graph["Prec"][3][0].to_numpy()
x5 = pp_graph["Prec"][4][0].to_numpy()
x6 = pp_graph["Prec"][5][0].to_numpy()
x7 = pp_graph["Prec"][6][0].to_numpy()
x8 = pp_graph["Prec"][7][0].to_numpy()
x9 = pp_graph["Prec"][8][0].to_numpy()
x10 = pp_graph["Prec"][9][0].to_numpy()
x11 = pp_graph["Prec"][10][0].to_numpy()
x12 = pp_graph["Prec"][11][0].to_numpy()
all_x = [x1,x2,x3,x4,x5,x6,x7,x8,x9, x10, x11, x12]

meses = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
box= ax.boxplot(all_x, patch_artist=True, labels=meses)
ax.set_ylabel("mm",rotation=0, ha='left', y=1)


ax2=ax.twinx()
x = np.arange(1,13)
ax2.plot(x,tmax_monthly["tx"].to_numpy(),label="Tmax", color="red")
ax2.plot(x,tmin_monthly["tmin"].to_numpy(),label="Tmin",color="blue")
plt.show()

fig, ax = plt.subplots(figsize=(9, 6))
ax2 = ax.twinx()  
ax2.set_ylim(0, 24)

x1 = pp_graph["Prec"][0][0].to_numpy()
x2 = pp_graph["Prec"][1][0].to_numpy()
x3 = pp_graph["Prec"][2][0].to_numpy()
x4 = pp_graph["Prec"][3][0].to_numpy()
x5 = pp_graph["Prec"][4][0].to_numpy()
x6 = pp_graph["Prec"][5][0].to_numpy()
x7 = pp_graph["Prec"][6][0].to_numpy()
x8 = pp_graph["Prec"][7][0].to_numpy()
x9 = pp_graph["Prec"][8][0].to_numpy()
x10 = pp_graph["Prec"][9][0].to_numpy()
x11 = pp_graph["Prec"][10][0].to_numpy()
x12 = pp_graph["Prec"][11][0].to_numpy()
all_x = [x1,x2,x3,x4,x5,x6,x7,x8,x9, x10, x11, x12]

meses = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
box= ax.boxplot(all_x, patch_artist=True, labels=meses)
ax.set_ylabel("mm",rotation=0, ha='left', y=1)

ax2.plot(x,tmax_monthly["tx"].to_numpy(),label="Tmax", color="red")
ax2.plot(x,tmin_monthly["tmin"].to_numpy(),label="Tmin",color="blue")
ax2.set_ylabel("C",rotation=0, ha='right', y=1)
x = np.arange(1,13)
plt.legend()
plt.grid()
plt.show()

"""# Fig 2b: solo pp"""

pp_filtro=PISCO_pp.sel(time=slice('1981-06-01T00:00:00.000000000','2010-05-31T12:00:00.000000000'))
pp_filtro

PISCO_pp.Prec.sel(time= slice('1981-06-01', '2010-05-31')).groupby('time.year').sum('time')

pp_anual = PISCO_pp.Prec.sel(time= slice('1981-06-01', '2010-05-31')).groupby('time.year').sum('time').mean('year')
pp_anual

fig, ax = plt.subplots(1, 1, figsize=(10, 8))
pp_anual.plot(ax=ax)
lugar = Sudamerica.plot(ax=ax,facecolor="none",edgecolor="black")
minx, miny, maxx, maxy = -73.5, -18.5, -67.5, -12.55
ax.set_xlim(minx, maxx)
ax.set_ylim(miny, maxy)

fig, ax = plt.subplots(1, 1, figsize=(10, 8))
pp_anual.plot(ax=ax, cmap ="YlGnBu", vmin=150, vmax=1100)
lugar = Sudamerica.plot(ax=ax,facecolor="none",edgecolor="black")
minx, miny, maxx, maxy = -73.5, -18.5, -67.5, -12.55
ax.set_xlim(minx, maxx)
ax.set_ylim(miny, maxy)

"""# Fig 2c: tmax"""

tmax_filtro=PISCO_tmax.sel(time=slice('1981-06-01T00:00:00.000000000','2010-05-31T12:00:00.000000000'))
tmax_filtro

tmax_anual = tmax_filtro.mean(dim="time").tx
tmax_anual

tmax_filtro.mean(dim="time").tx.plot(cmap="RdBu_r")

fig, ax = plt.subplots(1, 1, figsize=(10, 8))
tmax_anual.plot(ax=ax,cmap="RdBu_r",vmin=-30,vmax=30)
lugar = Sudamerica.plot(ax=ax,facecolor="none",edgecolor="black")
minx, miny, maxx, maxy = -73.5, -18.5, -67.5, -12.55
ax.set_xlim(minx, maxx)
ax.set_ylim(miny, maxy)

"""# Fig 2d: tmin"""

tmin_filtro=PISCO_tmin.sel(time=slice('1981-06-01T00:00:00.000000000','2010-05-31T12:00:00.000000000'))
tmin_filtro

tmin_anual = tmin_filtro.mean(dim="time").tmin
tmin_anual

fig, ax = plt.subplots(1, 1, figsize=(10, 8))
tmin_anual.plot(ax=ax,cmap="RdBu_r", vmin=-30,vmax=30)
lugar = Sudamerica.plot(ax=ax,facecolor="none",edgecolor="black")
minx, miny, maxx, maxy = -73.5, -18.5, -67.5, -12.55
ax.set_xlim(minx, maxx)
ax.set_ylim(miny, maxy)

"""# TODO JUNTO"""

from mpl_toolkits.mplot3d import axes3d
fig, axs = plt.subplots(2, 2, figsize=(11.5, 10))

#DIAGRAMA CLIMATOLOGICO
x1 = pp_graph["Prec"][0][0].to_numpy()
x2 = pp_graph["Prec"][1][0].to_numpy()
x3 = pp_graph["Prec"][2][0].to_numpy()
x4 = pp_graph["Prec"][3][0].to_numpy()
x5 = pp_graph["Prec"][4][0].to_numpy()
x6 = pp_graph["Prec"][5][0].to_numpy()
x7 = pp_graph["Prec"][6][0].to_numpy()
x8 = pp_graph["Prec"][7][0].to_numpy()
x9 = pp_graph["Prec"][8][0].to_numpy()
x10 = pp_graph["Prec"][9][0].to_numpy()
x11 = pp_graph["Prec"][10][0].to_numpy()
x12 = pp_graph["Prec"][11][0].to_numpy()
all_x = [x1,x2,x3,x4,x5,x6,x7,x8,x9, x10, x11, x12]
meses = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
#diagrama de cajas de pp
axs[0, 0].boxplot(all_x, patch_artist=True, labels=meses)
axs[0, 0].set_ylabel("mm",rotation=0, ha='left', y=1)
#tmax y tmin
ax1=axs[0, 0].twinx()
x = np.arange(1,13)
ax1.plot(x,tmax_monthly["tx"].to_numpy(),label="Tmax", color="red")
ax1.plot(x,tmin_monthly["tmin"].to_numpy(),label="Tmin",color="blue")
ax1.set_ylabel("°C",rotation=0, ha='right', y=1)

axs[0, 0].set_title('(a)', loc='left')
plt.legend()

#DIAGRAMA 2
ax2 = axs[0, 1]
pp_anual.plot(ax=ax2, cmap ="YlGnBu", vmin=150, vmax=1100)
lugar = Sudamerica.plot(ax=ax2,facecolor="none",edgecolor="black")
minx, miny, maxx, maxy = -73.5, -18.5, -67.5, -12.55
ax2.set_xlim(minx, maxx)
ax2.set_ylim(miny, maxy)
ax2.set_ylabel("")
ax2.set_yticks([])
axs[0, 1].set_title('(b)', loc='left')

#DIAGRAMA 3
ax3 = axs[1, 0]
tmax_anual.plot(ax=ax3,cmap="RdBu_r",vmin=-30,vmax=30, add_colorbar=False)
lugar = Sudamerica.plot(ax=ax3,facecolor="none",edgecolor="black")
lago = lago_titicaca.plot(ax=ax3,facecolor="paleturquoise",edgecolor="black")
minx, miny, maxx, maxy = -73.5, -18.5, -67.5, -12.55
ax3.set_xlim(minx, maxx)
ax3.set_ylim(miny, maxy)
axs[1, 0].set_title('(c)', loc='left')


#DIAGRAMA 4
ax4 = axs[1, 1]
tmin_anual.plot(ax=ax4,cmap="RdBu_r", vmin=-30,vmax=30)
lugar = Sudamerica.plot(ax=ax4,facecolor="none",edgecolor="black")
lago = lago_titicaca.plot(ax=ax4,facecolor="paleturquoise",edgecolor="black")
minx, miny, maxx, maxy = -73.5, -18.5, -67.5, -12.55
ax4.set_xlim(minx, maxx)
ax4.set_ylim(miny, maxy)
axs[1, 1].set_title('(d)', loc='left')